### ISSUE TITLE
Not clear how to use some flags

### ISSUE THREAD

**Issue by moldach** [biopet/vcffilter#12]
I've got a number of `0/0, 0/0, 0/0` reported in a VCF file so I will need to do some filtering.

I've never used `vcffilter` before and the manual isn't very clear for some parameters:

```
--deNovoInSample <sample>
                           Only show variants that contain unique alleles in complete set for given sample
  --deNovoTrio <child:father:mother>
```

It's not clear to me what I'm supposed to put in `<sample>` for example.

My VCF header looks like:

> #CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  ./proband_bwaMEM_sort_dedupped.bam      dad_bwaMEM_sort_dedupped.bam    mom_bwaMEM_sort_dedupped.bam

## 

```
$ java -jar ~/bin/vcffilter.jar -I proband_freebayes_filt_normalized_decompose.vcf -o filter.vcf --deNovoInSample proband

INFO  [2020-10-20 14:01:37,360] [VcfFilter$] - Start
Exception in thread "main" htsjdk.tribble.TribbleException$MalformedFeatureFile: Unable to parse header with error: /gpfs/home/moldach/projects/saliva/ensembl/deconseq/RUFUS-TRIO/proband_freebayes_filt_normalized_decompose.vcf, for input source: file:///gpfs/home/moldach/projects/saliva/ensembl/deconseq/RUFUS-TRIO/proband_freebayes_filt_normalized_decompose.vcf
	at htsjdk.tribble.TribbleIndexedFeatureReader.readHeader(TribbleIndexedFeatureReader.java:262)
	at htsjdk.tribble.TribbleIndexedFeatureReader.<init>(TribbleIndexedFeatureReader.java:101)
	at htsjdk.tribble.TribbleIndexedFeatureReader.<init>(TribbleIndexedFeatureReader.java:126)
	at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:110)
	at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:74)
	at htsjdk.variant.vcf.VCFFileReader.<init>(VCFFileReader.java:117)
	at htsjdk.variant.vcf.VCFFileReader.<init>(VCFFileReader.java:68)
	at nl.biopet.tools.vcffilter.VcfFilter$.main(VcfFilter.scala:45)
	at nl.biopet.tools.vcffilter.VcfFilter.main(VcfFilter.scala)
Caused by: java.nio.file.NoSuchFileException: /gpfs/home/moldach/projects/saliva/ensembl/deconseq/RUFUS-TRIO/proband_freebayes_filt_normalized_decompose.vcf
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at htsjdk.samtools.seekablestream.SeekablePathStream.<init>(SeekablePathStream.java:39)
	at htsjdk.tribble.util.ParsingUtils.openInputStream(ParsingUtils.java:108)
	at htsjdk.tribble.TribbleIndexedFeatureReader.readHeader(TribbleIndexedFeatureReader.java:252)
	... 8 more
```

**Comment by DavyCats** [comment]
I'm not too familiar with this tool or its options, to be honest, but I suspect you need to give the sample name as noted in the VCF file, so: `./proband_bwaMEM_sort_dedupped.bam`

And just as a heads up, this tool isn't really maintained anymore.
